name: filmy
description: "A new Flutter project."
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ^3.5.3


dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8
  dio: ^5.8.0+1
  hive: ^2.2.3
  validators: ^3.0.0
  cached_network_image: ^3.4.1
  flutter_spinkit: ^5.2.1
  flutter_svg: ^2.0.17
  loading_indicator: ^3.1.1
  intl: ^0.20.2
  build_runner: ^2.4.13
  hive_flutter: ^1.1.0
  hive_generator: ^2.0.1
  connectivity_plus: ^6.1.3
  internet_connection_checker: ^3.0.1
  cherry_toast: ^1.11.0
  workmanager: ^0.5.2
  melos: ^6.0.0
  change_app_package_name: ^1.4.0
  rename_app: ^1.6.2
  flutter_launcher_icons: ^0.14.3

dev_dependencies:
  flutter_test:
    sdk: flutter


  flutter_lints: ^4.0.0


flutter:


  uses-material-design: true

  assets:
    - assets/icons/


  fonts:
    - family: GothamBook
      fonts:
        - asset: assets/fonts/Gotham-Book.otf

